apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: nginx
          ports:
            - containerPort: 7007
          env:
            - name: BACKSTAGE_BASE_URL
              value: "http://34.142.76.63"
